apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: productionk8s
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/metadata-enrichment: "true"
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: https://SEU-AMBIENTE-DYNATRACE.NET/e/1004594-4d8d-4671d-86f4-3189005dd8da35/api
  skipCertCheck: true
  tokens: productionk8s
  networkZone: productionk8s

  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    group: productionk8s
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
